---
title: "Data Cleaning"
output: html_document
---

```{r}
games<-read.csv('Video games sales.csv')

nrow(games)
```
#cleaning null values

```{r}
games<-na.omit(games)
unique(games$Rating)
games$Rating <- ifelse(games$Rating== "", NA,games$Rating )
unique(games$Rating)
games<-subset(games,games$Rating!="NA")
games<-subset(games,games$Year_of_Release!="N/A")
nrow(games)
```

#Critic_Count	User_Score 

```{r}
library(ggplot2)
ggplot(games, aes(x = games$User_Score)) +
  geom_histogram(binwidth = 0.5, fill = "blue", color = "red", alpha = 0.7) +
  ggtitle("Histogram") +
  theme_minimal()

custom_colors <- c("#1f77b4", "#ff7f0e", "#2ca02c", "#d62728")

# Create a custom star-shaped point
star_point <- data.frame(x = 0, y = 0)

# Create an attractive box plot with outliers as stars
ggplot(games, aes(y = User_Score)) +
  geom_boxplot(color = "blue", fill = "lightblue", alpha = 0.7) +
  geom_point(data = star_point, aes(x = x, y = y), shape = 8, size = 2, color = custom_colors[2]) +
  theme_minimal() +
  scale_color_manual(values = custom_colors) +
  labs(y = "User Score") +
  ggtitle("Box Plot of User Scores ")

qqnorm(games$User_Score)
qqline(games$User_Score)

```

```{r}
```{r}
library(ggplot2)

critic_count_box<-ggplot(games,aes(y=Critic_Count))+geom_boxplot()
critic_count_hist<-ggplot(games,aes(x=Critic_Count))+geom_histogram(binwidth =5 ,fill='red',color='black')
qqnorm(games$Critic_Count)
qqline(games$Critic_Count)
```
```